# Standard operaring procedures

> Marie-Angélique Laporte, Almendra Cremaschi

An experimental protocol provides a standardised overview of the basic information that will be collected during a crop tricot trial. The protocol provides an overview of the data collection moments during the trials and the variables and traits collected at each data collection moment. Farmers evaluate varieties in their on-farm trials and provide comparative observations by ranking the varieties based on their performance throughout their growth and post-harvest qualities including taste and consumption preferences.


# Socio-economic sampling

> Béla Teeken, Jill Cairns

## Assuring experienced participants

A common weakness in standard participatory variety selections is that farmers are chosen without eye for their experience and the specific work they are doing and to which local social category they belong. Where this is considered usually very broad general categories are used such as age and sex., occupation, level of education, farm size. Furthermore, when gender is brought in focus, the practice is mainly on having both men and women farmers in equal numbers evaluating the trials, disregarding their specific expertise or experience in farming. Another problem is that often farmers get chosen who feel comfortable talking and interacting within the sphere of a scientific evaluation, which emphasizes experience in reasoning and talking. This often excludes very skilled persons that however are not able or are normatively not allowed to communicate these skills and knowledge through language. But even if the respondent is good at talking it still does not include the tacit knowledge, the embodied skill and knowledge that people have. Breeders are however interested in detailed concrete hands-on information if they want to align with a demand led breeding approach such as the stage gate breeding approach that is now introduced in the CGIAR public sector breeding. Within the current reform to a stage gate breeding approach it is also crucial to get feedback from not only farmers but also processors/prepares and marketers who turn the RTB crop into an edible quality food product.

To overcome these issues while choosing the TRICOT participants, we therefore work with a so-called purposive sampling using a task group approach with an explicit gender dimension. This gender dimension is not only important within the light of gender equity but is also very practical and concrete if we want to know the expertise and experience people have with regards to work related to the RTB corps because often tasks related to the RTB crop are gendered: certain tasks are often carried out be a specific sex. Important to note here is that a task group is not necessarily a group that works together but a category of people of the same social segment that carry out similar tasks related to the crop.
A task group approach is also in line with a much more performative way of participation instead of only a deliberative one (Richards, 2007) . In such a performative approach people who are verbally not strong or are not allowed to speak up are included and approached more self-evidently and tacitly, because they have been identified as a specific task group within a locally defined and thus relevant social group or intersection of different groups.

From a demand led perspective breeders are interested in good information on the suitability of improved varieties within the livelihoods of the users and therefore want to know the user preferred crop characteristics. To get good information it is therefore important to get this from experienced people that are skilled in farming but also with regards to processing of the crop into the food products and their quality as well as the marketing of the crop. Importantly storability of food products as well as fresh roots tubers and bananas are important in the last instance.  E.g if men are are hardly involved into processing cassava into gari , a breeder will not be interested much in men’s preferences with relation to processing because they will not always be able to give correct hands on experience-based knowledge because they do not possess the skill. Men in this case might have indirect knowledge about it (e.g. through their spouses), but certainly not the embodied skills.

A bad example of how participants got chosen is a farce case where someone wanted to work with mango farmers and ended up with only male participants of which non had a mango tree field. When later confronting these participants with this, the village chief and his friends all claimed to have a mango tree in their backyard. It is obvious that a tricot with such participants will not yield the best information.


| Locally Relevant Social Group*                     | Share of Local Population (oral or record share) [B1.4a] | Language (record language) [B1.4b] | Associated Livelihood(s) or Crops [B1.4c]                                           | Tasks Related to Cassava (Women)                      | Tasks Related to Cassava (Men)                          | Better Off Group(s)? (Yes=1, No=2) [B1.4d] | Politically Active & Influential Group(s)? (Yes=1, No=2) [B1.4e] |
|----------------------------------------------------|----------------------------------------------------------|-------------------------------------|------------------------------------------------------------------------------------|------------------------------------------------------|--------------------------------------------------------|------------------------------------------|---------------------------------------------------------------|
| i. Ilaje (originally from Ondo state)             | 1000                                                     | Yoruba dialect                      | Fishing, selling of fish                                                          |                                                      |                                                        | 2                                        | 2                                                             |
| ii. Agatu (Immigrants from Benue state)           | 500                                                      | Agatu                                | Farming (subsistence and cash crops), farm labourer. Includes cassava             | Farming (weeding, harvesting), processing, marketing | Farming (weeding, planting, harvesting), marketing of fresh roots | 2                                        | 2                                                             |
| iii. Markurdi (Immigrants from Benue state)       | 100                                                      | Tiv/Igede                            | Farming (subsistence and cash crops), farm labourer. Includes cassava             | Farming (weeding), processing, marketing            | Farming, marketing of fresh roots                        | 2                                        | 2                                                             |
| iv. Hausa                                         | 10                                                       | Hausa                                | Trading, fishing                                                                 |                                                      |                                                        | 2                                        | 2                                                             |
| v. Cotonou (Immigrants from Benin republic)       | 50                                                       | Fon/Ewe                              | Farming (subsistence and cash crops), particularly cultivate vegetables, tomatoes, and peppers. Includes cassava | Farming (planting, weeding), processing, marketing   | Farming and occasional processing                      | 2                                        | 2                                                             |
| vii. Fulani                                       | 150                                                      | Fulfulde                             | Cattle rearing                                                                    |                                                      |                                                        | 2                                        | 2                                                             |
| viii. Yoruba                                      | 18145                                                    | Yoruba                               | Farming (food and cash crops), trading. Includes cassava                          | More of processing, some farming (weeding), firm marketing | Farming, marketing of fresh roots                        | 1                                        | 1                                                             |



# Geographic sampling

> Joost van Heerwaarden, Jacob van Etten

# Target product profiles



